### ISSUE TITLE
Disable sorting on toJson / toArray

### ISSUE THREAD

**Issue by sandrokeil** [martin-schilling/php-velocypack#9]
At the moment JSON data is sorted which can lead to errors. `toJson` should return original data from `fromJson`.

**Comment by sandrokeil** [comment]
@martin-schilling It's described in the [docs](https://github.com/arangodb/velocypack/blob/3748d5c49295e28f5dd8d7dfd0278ff8b645829b/examples/API.md#building-vpack-objects-programmatically).

```c
Options options;
options.checkAttributeUniqueness = true;
options.sortAttributeNames = false;

Builder b(&options);
```

**Comment by martin-schilling** [comment]
Yes but it seems like that feature was removed 2 years ago: https://github.com/arangodb/velocypack/commit/985a1dcccad4ae0c876b1b7cb106971305725c08#diff-1f75eaa67fc2b9cdf6c00a241edcafcb
There is probably some other way of achieving this but I did not look into that yet.

**Comment by martin-schilling** [comment]
Thanks to the help of the velocypack devs I know how this can be achieved now. It simply requires not having an index at all by setting the necessary options like this:
```
        vp::Options options;
        options.buildUnindexedObjects = true;
        options.buildUnindexedArrays = true;
```
Therefore this feature can be implemented soon

**Comment by martin-schilling** [comment]
This can be achieved now by passing the following options to `fromArray` or `fromJsom`.
```
$vpack = \Velocypack\Vpack::fromJson('{"2":100,"1":1000000,"x":"test","d":true}', [
    Velocypack\Option\BUILD_UNINDEXED_OBJECTS => true,
    Velocypack\Option\BUILD_UNINDEXED_ARRAYS => true
])
```
I decided to leave the sorted version as the default for now since that is the official behaviour of to velocypack C++ implementation.
